import { Box, Container, Flex, Text } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import NewPostWizard from "~/components/NewPostWizard";
import Post from "~/components/Post";
import SearchBar from "~/components/SearchBar";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: posts } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Pets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as={"main"} mx={2} my={4}>
        <Flex gap={4} mb={4}>
          <SearchBar />
          <NewPostWizard />
        </Flex>
        <Container maxW="lg">
          {!posts?.length ? (
            <Text fontSize={"2xl"}>no posts to show</Text>
          ) : (
            posts.map((post) => <Post key={post.id} post={post} />)
          )}
        </Container>
      </Box>
    </>
  );
};

export default Home;
