import { Box, Flex, Text } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import NewPostWizard from "~/components/NewPostWizard";
import SearchBar from "~/components/SearchBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as={"main"} mx={2} my={4}>
        <Flex gap={4}>
          <SearchBar />
          <NewPostWizard />
        </Flex>
        <Text>Posts goes here...</Text>
      </Box>
    </>
  );
};

export default Home;
