import { Box, Center, Container, Flex, Text } from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import LoadingPost from "~/components/LoadingPost";
import NewPostWizard from "~/components/NewPostWizard";
import Post from "~/components/Post";
import SearchBar from "~/components/SearchBar";
import { api } from "~/utils/api";

// todo fix 0 from empty results

const Home: NextPage = () => {
  const { data: posts, isLoading } = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Pets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as={"main"} mx={2} my={4}>
        <Flex gap={4} mb={4}>
          <SearchBar />
          <NewPostWizard />
        </Flex>
        <Container maxW="lg">
          {isLoading && <LoadingPost quantity={2} />}
          {!isLoading && posts?.length && (
            <>
              {posts?.map((post) => (
                <Post key={post.id} post={post} />
              ))}
            </>
          )}
          {!isLoading && !posts?.length && (
            <Center>
              <Text fontSize={"2xl"}>User has no posts.</Text>
            </Center>
          )}
        </Container>
      </Box>
    </>
  );
};

export default Home;
